services:
  frontend:
    image: sunilak05/devops-intel-frontend:latest   # or use :${TAG} managed by deployment script
    ports:
      - "80:80"

  backend:
    image: sunilak05/devops-intel-backend:latest
    ports:
      - "8080:8080"
